enum Projects {
  basic = "basic",
  advanced = "advanced",
  authorSupervision = "authorSupervision",
  comprehensive = "comprehensive",
}

export type Project = keyof typeof Projects;

type PortfolioProject = {
  projectId: string;
  name: string;
  image: string;
  images?: string[];
  shortDescription?: string;
  description?: string;
};

export const PortfolioProjects: PortfolioProject[] = [
  {
    projectId: "kompleks-wypoczynkowy-pod-warszawa",
    name: "Filozofia slow life",
    image: "/images/kompleks-wypoczynkowy-pod-warszawa/1.jpg",
    images: [
      "/images/kompleks-wypoczynkowy-pod-warszawa/1.jpg",
      "/images/kompleks-wypoczynkowy-pod-warszawa/2.jpg",
      "/images/kompleks-wypoczynkowy-pod-warszawa/3.jpg",
      "/images/kompleks-wypoczynkowy-pod-warszawa/4.jpg",
      "/images/kompleks-wypoczynkowy-pod-warszawa/5.jpg",
      "/images/kompleks-wypoczynkowy-pod-warszawa/6.jpg",
    ],
    shortDescription: "Koncepcja kompleksu wypoczynkowego pod Warszawą",
    description: `Projekt ten znajduje się obecnie w fazie aktywnego rozwoju i projektowania, gdzie krok po kroku tworzymy miejsce, w którym architektura całkowicie wtapia się w dziką przyrodę. Proste, ciemne sylwetki domów w stylu A-frame oraz Barnhouse są starannie wkomponowane między pnie sosen, nie zakłócając ciszy i spokoju tego miejsca. Głównym wyróżnikiem przestrzeni stała się kręta sieć kanałów: domki są usytuowane tak, że każdy z nich zyskał swoją kameralną mikro-wyspę oraz prywatny pomost z zacumowaną łódką tuż przy progu. Nie ma tu asfaltu ani wysokich płotów – jedynie żwirowe ścieżki, drewniane mostki, ogromne okna panoramiczne wpuszczające do środka leśną mgłę oraz wspólne palenisko na piaszczystym brzegu otwartej wody. To minimalistyczna i pełna życia przestrzeń, stworzona w jednym celu – aby podarować to wyjątkowe, tak dziś rzadkie uczucie leśnej samotności, dla którego chce się uciec z głośnego miasta.`,
  },
  {
    projectId: "budynek-w-lublinie",
    name: "Budynek w Lublinie",
    image: "/images/budynek-w-lublinie/1.jpg",
    images: [
      "/images/budynek-w-lublinie/1.jpg",
      "/images/budynek-w-lublinie/2.jpg",
      "/images/budynek-w-lublinie/3.jpg",
      "/images/budynek-w-lublinie/4.jpg",
      "/images/budynek-w-lublinie/5.jpg",
      "/images/budynek-w-lublinie/6.jpg",
      "/images/budynek-w-lublinie/7.jpg",
      "/images/budynek-w-lublinie/8.jpg",
      "/images/budynek-w-lublinie/10.jpg",
      "/images/budynek-w-lublinie/11.jpg",
      "/images/budynek-w-lublinie/12.jpg",
    ],
    description: "Powierzchnia domu 140 m2",
  },
  {
    projectId: "budynek-w-warszawie",
    name: "Budynek w Warszawie",
    image: "/images/house/pc09-7.jpg",
    images: [
      "/images/house/pc09-7.jpg",
      "/images/house/cc15-3.jpg",
      "/images/house/cc18-2.jpg",
      "/images/house/cc19-4.jpg",
      "/images/house/cc28-3.jpg",
      "/images/house/cc29-2.jpg",
      "/images/house/cc14-1.jpg",
      "/images/house/cc30-2.jpg",
      "/images/house/cc32-2.jpg",
      "/images/house/cc34-1.jpg",
      "/images/house/8FGZxxDJxUMp.jpg",
      "/images/house/pc03-8.jpg",
      "/images/house/pc18-5.jpg",
      "/images/house/pc04-9.jpg",
      "/images/house/pc05-1.jpg",
      "/images/house/pc06-4.jpg",
      "/images/house/pc07-5.jpg",
      "/images/house/pc08-6.jpg",
      "/images/house/pc10-2.jpg",
      "/images/house/pc11-3.jpg",
      "/images/house/pc12-4.jpg",
      "/images/house/pc13-5.jpg",
      "/images/house/pc14-1-1.jpg",
      "/images/house/pc14-10.jpg",
      "/images/house/pc15-1.jpg",
      "/images/house/pc16-3.jpg",
      "/images/house/pc17-4.jpg",
      "/images/house/pc19-6.jpg",
    ],
    description: "Powierzchnia domu 298 m2",
  },
  {
    projectId: "budynek-w-katarze-2",
    name: "Budynek w Katarze",
    image: "/images/qatar2/A. Kuwari Villa & Majlis Design updated-2.jpg",
    images: [
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-2.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-3.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-4.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-5.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-6.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-7.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-8.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-9.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-10.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-11.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-12.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-13.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-14.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-15.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-16.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-17.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-18.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-19.jpg",
      "/images/qatar2/A. Kuwari Villa & Majlis Design updated-20.jpg",
    ],
    description: "Powierzchnia domu 600 m2",
  },
  {
    projectId: "lodz-gdanska-24",
    name: "Łódż. Gdańska 24",
    image: "/images/lodz-gdanska-24/4.jpg",
    images: [
      "/images/lodz-gdanska-24/4.jpg",
      "/images/lodz-gdanska-24/1.jpg",
      "/images/lodz-gdanska-24/2.jpg",
      "/images/lodz-gdanska-24/3.jpg",
      "/images/lodz-gdanska-24/5.jpg",
      "/images/lodz-gdanska-24/6.jpg",
      "/images/lodz-gdanska-24/7.jpg",
      "/images/lodz-gdanska-24/8.jpg",
      "/images/lodz-gdanska-24/9.jpg",
      "/images/lodz-gdanska-24/10.jpg",
    ],
    shortDescription: "Powierzchnia mieszkania 102 m2",
    description: `Przekształcone mieszkanie w centrum Łodzi na wynajem krótkoterminowy!
Mieszkanie w kamienicy, całkowicie odnowione i przystosowane do komfortowego wynajmu krótkoterminowego. Idealny wybór dla turystów. Mieszkanie z nowoczesnym wnętrzem zapewnia wygodny pobyt. Projekt został zrealizowany dla klienta, który specjalizuje się w wynajmie mieszkań na doby.`,
  },
  //   {
  //     projectId: "warszawa-marcina-kasprzaka-29A",
  //     name: "Warszawa, Marcina Kasprzaka 29A",
  //     image: "/images/warszawa-marcina-kasprzaka-29A/2.jpg",
  //     images: [
  //       "/images/warszawa-marcina-kasprzaka-29A/1.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/2.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/3.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/4.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/5.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/6.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/7.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/8.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/9.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/10.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/11.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/12.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/13.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/14.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/15.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/16.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/17.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/18.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/19.jpg",
  //       "/images/warszawa-marcina-kasprzaka-29A/20.jpg",
  //     ],
  //     shortDescription: "Kompleksowy remont biura VIPOL Group — od A do Z!",
  //     description: `Jako firma budowlano-remontowa mieliśmy przyjemność zrealizować ten projekt od podstaw. Zajęliśmy się wszystkim: od stanu surowego aż po finalne wykończenia, dbając o każdy szczegół.
  // Co zrobiliśmy?
  // Kompleksowe prace remontowe i budowlane
  // Nowoczesne wykończenia ścian, sufitów i podłóg
  // Montaż oświetlenia i detali, które podkreślają charakter przestrzeni
  // Biuro, które łączy nowoczesność z funkcjonalnością i dbałością o detale.
  // Solidne wykonanie sprawia, że przestrzeń jest nie tylko estetyczna, ale i praktyczna.
  // Cieszymy się, że mogliśmy zrealizować ten projekt od początku do końca!`,
  //   },
  //   {
  //     projectId: "warszawa-herbu-oksza-9",
  //     name: "Warszawa. Herbu Oksza 9",
  //     image: "/images/warszawa-herbu-oksza-9/1.jpg",
  //     images: [
  //       "/images/warszawa-herbu-oksza-9/1.jpg",
  //       "/images/warszawa-herbu-oksza-9/2.jpg",
  //       "/images/warszawa-herbu-oksza-9/3.jpg",
  //       "/images/warszawa-herbu-oksza-9/4.jpg",
  //     ],
  //     shortDescription: "Dwie nowe łazienki",
  //     description: `Dwie nowe łazienki — praca zakończona!
  // Nasz zespół ukończył projekt remontu dwóch łazienek. Wszystko zgodnie z planem, na czas i z uwzględnieniem oczekiwań klienta.
  // Co zrobiliśmy:
  // Pełna wymiana instalacji.
  // Układanie płytek i montaż armatury.
  // Instalacja oświetlenia i akcesoriów.
  // Czysto, starannie i solidnie. Jeśli potrzebujecie remontu, który spełni Wasze oczekiwania, skontaktujcie się z nami — wykonamy wszystko rzetelnie!`,
  //   },
  {
    projectId: "silownia-w-katarze",
    name: "Siłownia w budynku",
    image: "/images/qatar3/1.jpg",
    images: [
      "/images/qatar3/1.jpg",
      "/images/qatar3/2.jpg",
      "/images/qatar3/3.jpg",
      "/images/qatar3/4.jpg",
    ],
    description: "Katar",
  },
  {
    projectId: "mieszkanie-w-katarze",
    name: "Mieszkanie w Katarze",
    image: "/images/qatar4/living.jpg",
    images: [
      "/images/qatar4/living.jpg",
      "/images/qatar4/living 3.jpg",
      "/images/qatar4/living 2.jpg",
      "/images/qatar4/living 4.jpg",
      "/images/qatar4/BED 2.jpg",
      "/images/qatar4/hallway v2.jpg",
    ],
    description: "Powierzchnia mieszkania 117 m2",
  },
  {
    projectId: "budynek-w-katarze-1",
    name: "Budynek w Katarze",
    image: "/images/qatar1/A. Jufairi - master updated-17.jpg",
    images: [
      "/images/qatar1/A. Jufairi - master updated-17.jpg",
      "/images/qatar1/A. Jufairi - master updated-3.jpg",
      "/images/qatar1/A. Jufairi - master updated-4.jpg",
      "/images/qatar1/A. Jufairi - master updated-5.jpg",
      "/images/qatar1/A. Jufairi - master updated-6.jpg",
      "/images/qatar1/A. Jufairi - master updated-7.jpg",
      "/images/qatar1/A. Jufairi - master updated-8.jpg",
      "/images/qatar1/A. Jufairi - master updated-13.jpg",
      "/images/qatar1/A. Jufairi - master updated-15.jpg",
      "/images/qatar1/A. Jufairi - master updated-16.jpg",
      "/images/qatar1/A. Jufairi - master updated-18.jpg",
      "/images/qatar1/A. Jufairi - master updated-19.jpg",
      "/images/qatar1/A. Jufairi - master updated-21.jpg",
      "/images/qatar1/A. Jufairi - master updated-22.jpg",
      "/images/qatar1/A. Jufairi - master updated-23.jpg",
      "/images/qatar1/A. Jufairi - master updated-24.jpg",
    ],
    description: "Powierzchnia domu 350 m2",
  },
    {
    projectId: "apartament-w-katalonii-hiszpania",
    name: "Apartament w Katalonii, Hiszpania",
    image: "/images/apartament-w-katalonii-hiszpania/1.jpg",
    images: [
      "/images/apartament-w-katalonii-hiszpania/1.jpg",
      "/images/apartament-w-katalonii-hiszpania/2.jpg",
      "/images/apartament-w-katalonii-hiszpania/3.jpg",
      "/images/apartament-w-katalonii-hiszpania/4.jpg",
      "/images/apartament-w-katalonii-hiszpania/5.jpg",
      "/images/apartament-w-katalonii-hiszpania/6.jpg",
      "/images/apartament-w-katalonii-hiszpania/7.jpg",
    ],
    description: "Powierzchnia apartamentu 80 m2",
  },
  {
    projectId: "lodz-al-tadeusza-kosciuszki-32",
    name: "Łódź. Al. Tadeusza Kościuszki 32",
    image: "/images/lodz-al-tadeusza-kosciuszki-32/23.jpg",
    images: [
      "/images/lodz-al-tadeusza-kosciuszki-32/23.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/1.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/2.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/3.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/4.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/5.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/6.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/7.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/8.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/9.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/10.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/11.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/12.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/13.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/14.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/15.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/16.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/17.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/18.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/19.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/20.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/21.jpg",
      "/images/lodz-al-tadeusza-kosciuszki-32/22.jpg",
    ],
    shortDescription: "Powierzchnia mieszkania 128 m2",
    description: `Kolejna realizacja w Łódzkiej kamienicy! Tym razem zaprojektowaliśmy i wykonaliśmy mieszkanie od A do Z dla firmy zajmującej się wynajmem krótkoterminowym i długoterminowym.
Z jednego dużego mieszkania stworzyliśmy 5 nowoczesnych apartamentów, które łączą funkcjonalność z wyjątkowym stylem.`,
  },
];
